### ISSUE TITLE
OmegleSpyWPF Issue 

### ISSUE THREAD

**Issue by Nannnerz** [jeanluc162/Omegle-.NET#4]
yah i cant make an issue for your other project but it crashes when you open it and its because of the Reference  PresentationCore.dll and the issue is located in System.Windows.Interop/HwndTarget Line 588: result = new IntPtr(Marshal.GetHRForException(ex)); 

Error: System.NullReferenceException : Object reference not set to an instance of an object 

and idk how to fix it soooo please make an update

**Comment by jeanluc162** [comment]
I'm sorry to hear that,

but the [OmegleSpyWPF](https://github.com/jeanluc162/OmegleSpyWPF)-Project is archived because I feel like it's "finished" and I don't want to work on it anymore.
I never experienced that error on any System I started it on, so it's most likely an issue with your PC. Feel free to fork the project and work on it, if you don't want to there are other solutions for accomplishing the same goal. See:
https://github.com/ash47/OmegleMiddleMan
https://github.com/olegberman/mitm-omegle
